name: CI/CD frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: frontend-app
      FILE: 'src/Constants/Url.jsx'
      CONNECTION_STRING:   'export const BASE_URL = "http://64.23.144.63/api";'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Mofify connection url
        run: |
          echo -e '${{ env.CONNECTION_STRING }}' > temp
          tail -n +2 ${{ env.FILE }} >> temp
          mv temp ${{ env.FILE }}
          cat ${{ env.FILE }}
        
      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Push Docker Image to Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag ${{env.IMAGE_NAME}} ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:latest
  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Deploy to Production
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.SERVER_IP }}
           username: root
           password: ${{ secrets.SERVER_PASSWORD }}
           script: |
             cd ~
             docker-compose -f docker-compose.frontend.yml down
             docker-compose -f docker-compose.frontend.yml pull
             docker-compose -f docker-compose.frontend.yml up -d
             echo "Container deployed"


